openapi: 3.0.1
info:
  title: TMK Brain
  description: |-
    This documentation contains endpoints available for TMK Brain.
  version: 0.0.1
servers:
  - url: http://localhost:3001/api/v1
    description: localhost for devs
paths:
  /health-check:
    get:
      tags:
        - Health Check
      description: Returns the status of the API
      responses:
        "200":
          $ref: "#/components/responses/HealthCheckResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
          
  /users/validate-email:
    post:
      tags:
        - Users
      description: Checks if the email is already existing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/ValidateEmail'
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  email_addess:
                    type: string
                    enum: 
                    - emailaddress@gmail.com
                  existing:
                    type: boolean
                    enum: 
                    - true
                    - false
  
  /users/register:
    post:
      tags:
        - Users
      description: Register customer account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/CreateCustomerAccount'
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum: 
                    - Successfully created customer account.
        "500":
          $ref: "#/components/responses/ErrorRegister"
          
  /users/enroll:
    post:
      tags:
        - Users
      description: Enroll employee account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/EnrollEmployeeAccount'
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum: 
                    - Successfully enrolled employee account.
        "500":
          $ref: "#/components/responses/ErrorRegister"

  /users/login:
    post:
      tags:
        - Users
      description: Customer login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/Login'
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  user_id:
                    type: number
                  permissions:
                    type: array
                    items:
                      type: string
                    example:
                      - "punch_in_out"
                      - "attendance"
                      - "manage_attendance"
                      - "manage_payroll"
                      - "payslips"
                      - "user_profile"
                      - "manage_users"
                      - "file_management"
                      - "ai_chat"
                  expires_in:
                    type: number
                    description: in seconds
                  token_type:
                    type: string
                    enum: 
                    - Bearer
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ErrorLogin"
          
  /users/{employee_id}:
    get:
      tags:
        - Users
      description: Get employee data
      parameters:
        - $ref: '#/components/parameters/EmployeeIdPathParam'
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Employee'
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ErrorGetEmployee"

  /plans:
    get:
      tags:
        - Plans
      description: Returns the plans available for subscription
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Plans'
                  
  /users/{employee_id}/attendance:
    get:
      tags:
        - Attendace
      description: Get employee attendance
      parameters:
        - $ref: '#/components/parameters/EmployeeIdPathParam'
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceRecord'
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ErrorGetAttendance"
          
  /users/{employee_id}/login:
    post:
      tags:
        - Attendace
      description: Employee punch in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/PunchInOut'
      parameters:
        - $ref: '#/components/parameters/EmployeeIdPathParam'
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum: 
                    - Successfully saved log in time.
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ErrorEmployeeLogin"
          
  /users/{employee_id}/logout:
    post:
      tags:
        - Attendace
      description: Employee punch out
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/PunchInOut'
      parameters:
        - $ref: '#/components/parameters/EmployeeIdPathParam'
      responses:
        "200": 
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum: 
                    - Successfully saved log out time. Total hours rendered for the day is N hours.
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/ErrorEmployeeLogout"
          
components:
  parameters:
    EmployeeIdPathParam:
      name: employee_id
      in: path
      required: true
      schema:
        type: number
      description: The ID of the employee
      
  schemas:
    AttendanceRecord:
      type: object
      properties:
        attendance_id:
          type: integer
          example: 1
        time_in:
          type: string
          format: date-time
          example: "2024-11-01T08:00:00.000Z"
        time_out:
          type: string
          format: date-time
          example: "2024-11-01T17:00:00.000Z"
        hours_rendered:
          type: integer
          example: 9
          
    CreateCustomerAccount:
      required: [email_address, stripe_id, plan_id, password, first_name, last_name, address, paid_amount]
      properties:
        email_address:
          type: string
        stripe_id:
          type: string
        plan_id:
          type: number
          description: The plan the customer subscribed to
        password:
          type: string
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        address:
          type: string
        paid_amount:
          type: number
          
    EnrollEmployeeAccount:
      required: [email_address, first_name, last_name, birthday]
      properties:
        email_address:
          type: string
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        birthday:
          type: string
          description: should be in YYYY-MM-DD format
    
    Employee:
      type: object
      properties:
        employee_id:
          type: integer
          example: 3
        first_name:
          type: string
          example: "Josiah"
        middle_name:
          type: string
          example: "Perez"
        last_name:
          type: string
          example: "Cavitana"
        birthday:
          type: string
          format: date
          example: "1998-04-15"
        email_address:
          type: string
          format: email
          example: "jaypcavitana3@gmail.com"
        address_1:
          type: string
          example: "Test"
        address_2:
          type: string
          example: "Test"
        city:
          type: string
          example: "Test"
        state:
          type: string
          example: "Test"
        zip_code:
          type: string
          example: "1600"
        country:
          type: string
          example: "Philippines"
        joining_date:
          type: string
          format: date
          example: "2024-01-01"
        status:
          type: string
          example: "Regular"
        division:
          type: string
          example: "IT"
        department:
          type: string
          example: "IT"
        job_title:
          type: string
          example: "Software Engineer"
        manager:
          type: object
          properties:
            first_name:
              type: string
              example: "Marco"
            middle_name:
              type: string
              example: "Guevara"
            last_name:
              type: string
              example: "Guevara"
    
    Login:
      required: [email_address, password]
      properties:
        email_address: 
          type: string
        password:
          type: string
    
    Plans:
      properties:
        plan_id:
          type: number
        plan_name:
          type: string
        description:
          type: string
        price:
          type: number
        features:
          type: object
          properties:
            feature_id:
              type: number
            feature_name:
              type: string
            description:
              type: string
              
    PunchInOut:
      required: [timestamp]
      properties:
        timestamp: 
          type: string
          description: timestamp in ISO format (e.g. 2024-11-01T08:00:00.000Z)
    
    ValidateEmail:
      required: [email_address]
      properties:
        email_address:
          type: string

  responses:
    SuccessResponse:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Success message
              status:
                type: integer
                description: HTTP status code

    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                enum: 
                - 1001
                type: number
              message:
                type: string
                enum:
                  - Wrong email or password.
    
    HealthCheckResponse:
      description: >-
        OK -- The request is a success; the status of the API will be returned
        in the response.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                description: Status of the API
                type: string
                enum:
                  - up
              version:
                description: Version of the API
                type: string
              info:
                description: Detailed information about the status of the API
                type: string
              timestamp:
                description: Date and time of the request
                type: string
              env:
                description: Environment
                type: string
                enum:
                  - dev
                  - stg
                  - prd
                  - local
    
    InternalServerError:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Unknown error occurred

    ErrorEmployeeLogin:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Please check request schema. Please refer to the openAPI documentation for the right endpoint usage.
                  - Please provide numeric employee ID.
                  - Unable to save punch in.
                  
    ErrorEmployeeLogout:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Please check request schema. Please refer to the openAPI documentation for the right endpoint usage.
                  - Please provide numeric employee ID.
                  - Unable to save punch out.
                  
    ErrorGetAttendance:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Please provide numeric employee ID.
                  
    ErrorGetEmployee:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Please provide numeric employee ID.
                  - Employee ID does not exist in our record.
                  
    ErrorLogin:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Please check request schema. Please refer to the openAPI documentation for the right endpoint usage.
                  - Email address does not exist in our records.

    ErrorRegister:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Please check request schema. Please refer to the openAPI documentation for the right endpoint usage.
                  - Email address already exists.
                  - Customer Stripe ID already exists.
                  - Plan ID does not exist.
                  - Unable to save customer account.
                  - Unable to enroll employee account.