openapi: 3.0.1
info:
  title: Boilerplate
  description: |-
    This is a simple API boilerplate.
  version: 0.0.1
servers:
  - url: http://localhost:3001/api/v1
    description: localhost for devs
paths:
  /health-check:
    get:
      tags:
        - Health Check
      description: Returns the status of the API
      responses:
        "200":
          $ref: "#/components/responses/HealthCheckResponse"
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/login:
    post:
      tags:
        - Login
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username or email
                password:
                  type: string
                  description: User's password
              required:
                - username
                - password
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Access token for authenticated requests
                  expires_in:
                    type: integer
                    description: Duration in seconds for which the token is valid
                  token_type:
                    type: string
                    description: Type of token (e.g., Bearer)
                  company_logo:
                    type: string
                    description: URL for company logo
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                  status:
                    type: integer
                    description: HTTP status code
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  
  /users:
    get:
      tags:
        - Users
      summary: List of all employee
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    profile_picture:
                      type: string
                      description: Image src of the profile picture of the employee
                    full_name:
                      type: string
                      description: Employee's full name
                    employee-id:
                      type: number
                      description: Employee's ID
                    status:
                      type: string
                      description: Employment status of the employee
                    department:
                      type: string
                      description: Employee's department
                    shift:
                      type: string
                      description: Employee's shift / schedule
                    joining_date:
                      type: string
                      format: date
                      description: Employee's date of employment
                    role:
                      type: string
                      description: Employee's role
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/dashboard:
    get:
      tags:
        - Users
      summary: User Dashboard
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  employee_fname:
                    type: string
                    description: First name of the employee
                  employee_mname:
                    type: string
                    description: Middle name of the employee
                  employee_lname:
                    type: string
                    description: Last name of the employee
                  email_address:
                    type: string
                    description: Email address of the user
                  company_name:
                    type: string
                    description: Name of the company
                  company_logo:
                    type: string
                    description: URL for company logo
                  today_worked_hours:
                    type: string
                    description: number of hours worked today
                  today_scheduled_hours:
                    type: string
                    description: number of hours scheduled today
                  today_remaining_hours:
                    type: string
                    description: number of hours remaining today
                  monthly_scheduled_hours:
                    type: string
                    description: number of hours scheduled for the month
                  monthly_worked_hours:
                    type: string
                    description: number of hours worked for the month
                  monthly_remaining_hours:
                    type: string
                    description: number of hours remaining for the month
                  monthly_overtime_hours:
                    type: string
                    description: number of hours overtime for the month
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/attendance:
    get:
      tags:
        - Users
      summary: User Attendance
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                      description: Date of the attendance record
                    in:
                      type: string
                      format: time
                      description: Punch in time
                    out:
                      type: string
                      format: time
                      description: Punch out time or null if not available
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - Users
      summary: Record User Attendance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_timestamp:
                  type: string
                  format: date-time
                  description: Date timestamp in UTC format
              required:
                - date_timestamp
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  status:
                    type: integer
                    description: HTTP status code
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/schedule:
    get:
      tags:
        - Users
      summary: User Schedule
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                      description: Date of the schedule
                    in:
                      type: string
                      format: time
                      description: Punch in time
                    out:
                      type: string
                      format: time
                      description: Punch out time
                    day:
                      type: string
                      description: Day equivalent of the date
                    hours:
                      type: string
                      format: time
                      description: Hours scheduled for the day
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /banners:
    get:
      tags:
        - Banners
      summary: Get Banners
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  banner_id:
                    type: integer
                    description: Unique ID of the banner
                  banner_image_url:
                    type: string
                    description: URL of the banner image
                  banner_description:
                    type: string
                    description: Description of the banner content
                  banner_title:
                    type: string
                    description: Title of the banner
                  created_date:
                    type: string
                    description: Date the banner was created
        "406":
          $ref: "#/components/responses/NotAcceptableError"
        "500":
          $ref: "#/components/responses/InternalServerError"
          
components:
   
  responses:
    HealthCheckResponse:
      description: >-
        OK -- The request is a success; the status of the API will be returned
        in the response.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                description: Status of the API
                type: string
                enum:
                  - up
              version:
                description: Version of the API
                type: string
              info:
                description: Detailed information about the status of the API
                type: string
              timestamp:
                description: Date and time of the request
                type: string
              env:
                description: Environment
                type: string
                enum:
                  - dev
                  - stg
                  - prd
                  - local
    NotAcceptableError:
      description: >-
        Not Acceptable -- The request has invalid Accept header.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Unsupported Accept header. Only application/json is
                    supported.
    InternalServerError:
      description: >-
        Interval Server Error -- There was a problem with the system itself the
        request cannot be completed.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
                enum:
                  - Unknown error occurred